name: Build Pkgs

on:
  workflow_dispatch:
  
jobs:
  build-pkg:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BRANCH: [unstable, testing, stable]
    steps:
      - name: Set up swap space
        uses: pierotofy/set-swap-space@v1.0
        with:
          swap-size-gb: 10
          
      - uses: Ste74/build-pkgs@main
        with:
          repo-src: "https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.manjaro.org/security-overlay/chromium"
          gitlab-user: ${{ secrets.GITLAB_USER }}
          gitlab-pw: ${{ secrets.GITLB_SERVER_USER}}
          user-mail: ${{ secrets.MANJARO_MAIL }}
          manjaro-user: ${{ secrets.MANJARO_USER }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          branch: ${{ matrix.branch }}
          gpg-key: ${{ secrets.GPG_SIGNING_KEY }}
          gpg-key-sign: ${{ secrets.GPG_SIGN }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
